/**
 * ShopERP Pro — License Crypto Engine (server-side)
 * ───────────────────────────────────────────────────
 * Node port of the same algorithm used by the desktop app's client-side
 * engine (app/ShopERP_Pro_v8.html). Keeping the algorithm + secret
 * identical means keys generated by either side always validate on
 * both sides.
 *
 * SECURITY: This file must never be sent to a browser. It is required
 * only by server/local.js (or other Node-side server code).
 */
'use strict';

// Must match MASTER_SECRET in app/ShopERP_Pro_v8.html exactly — do not change
// without also changing the client copy, or existing keys stop validating.
const MASTER_SECRET = 'SH0P3RP0-PR0-M4ST3R-K3Y-D33P4K-2025-X9Z';

// Fixed placeholder machine ID used for web/hosted (not device-locked) keys.
// Must match WEB_LICENSE_MID in app/ShopERP_Pro_v8.html exactly.
const WEB_LICENSE_MID = 'WEBHOSTEDNOMID00';

const PLANS = {
  daily:      { label: '1 Day',       days: 1,     code: 55, testOnly: true },
  weekly:     { label: '1 Week',      days: 7,     code: 66, testOnly: true },
  monthly:    { label: 'Monthly',     days: 30,    code: 11 },
  halfyearly: { label: 'Half-Yearly', days: 180,   code: 22 },
  yearly:     { label: 'Yearly',      days: 365,   code: 33 },
  lifetime:   { label: 'Lifetime',    days: 36500, code: 44 },
};

const CS = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';

function fnv32(str) {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = ((h & 0xffff) * 0x01000193 + ((h >>> 16) * 0x01000193 << 16)) & 0xffffffff;
  }
  return h >>> 0;
}

function enc(num, len) {
  let s = '', n = (num >>> 0);
  for (let i = 0; i < len; i++) { s = CS[n % CS.length] + s; n = Math.floor(n / CS.length); }
  return s;
}

function computeSegments(mid, planCode, expiryDays) {
  const eD = (expiryDays >>> 0);
  const pC = (planCode >>> 0);
  const base = mid + '|' + pC + '|' + eD + '|' + MASTER_SECRET;
  const h1 = fnv32(base + '~S1');
  const h2 = fnv32(base + '~S2');
  const h3 = fnv32(base + '~S3');
  const h4 = fnv32(base + '~S4');
  const x1 = (h1 ^ ((eD & 0xFFFF) * pC)) >>> 0;
  const x2 = (h2 ^ (pC * 0x9E37)) >>> 0;
  const x3 = (h3 ^ (eD >> 4)) >>> 0;
  const x4 = (h4 ^ (pC << 8)) >>> 0;
  return [enc(x1, 4), enc(x2, 4), enc(x3, 4), enc(x4, 4)];
}

function normalizeMid(machineId) {
  return (machineId || '').replace(/-/g, '').toUpperCase().padEnd(16, '0').substring(0, 16);
}

function generateKey(machineId, plan) {
  const p = PLANS[plan];
  if (!p) throw new Error('Unknown plan: ' + plan);
  const mid = normalizeMid(machineId);
  const todayDays = Math.floor(Date.now() / 86400000);
  const expiryDays = (todayDays + p.days) >>> 0;
  const segs = computeSegments(mid, p.code, expiryDays);
  return segs.join('-');
}

// Decodes a key against a machineId by brute-forcing plan x issue-date
// combinations, same approach as the client's validateKey().
function decodeKey(key, machineId) {
  const clean = (key || '').replace(/-/g, '').toUpperCase();
  if (clean.length !== 16) return { valid: false, message: 'Key must be 16 characters' };
  for (const c of clean) {
    if (CS.indexOf(c) < 0) return { valid: false, message: 'Invalid character in key: ' + c };
  }
  const mid = normalizeMid(machineId);
  const todayDays = Math.floor(Date.now() / 86400000);

  for (const [planId, p] of Object.entries(PLANS)) {
    for (let ago = 0; ago <= p.days; ago++) {
      const expiryDays = (todayDays - ago + p.days) >>> 0;
      const segs = computeSegments(mid, p.code, expiryDays);
      if (segs.join('') === clean) {
        const daysLeft = Math.max(0, expiryDays - todayDays);
        const expired = daysLeft <= 0;
        const expDate = new Date(expiryDays * 86400000).toISOString().split('T')[0];
        return { valid: true, expired, plan: planId, planLabel: p.label, expiryDate: expDate, daysLeft };
      }
    }
  }
  return { valid: false, message: 'Key is invalid or belongs to a different machine' };
}

module.exports = { PLANS, MASTER_SECRET, WEB_LICENSE_MID, generateKey, decodeKey, normalizeMid };
